### ISSUE TITLE
xBPQ文件夹里面有几个同名文件，解压后会提示覆盖

### ISSUE THREAD

**Issue by cnnbgo** [gaotianliuyun/gao#14]
xBPQ文件夹里面有几个同名文件，解压后会提示覆盖

Github居然支持同文件夹同名，下载解压后就不行了

**Comment by gaotianliuyun** [comment]
其实你认真看的话并不同名，两个文件大小写不一样，但是在解压缩时不支持区分大小写解压，就导致了覆盖的问题，这种情况我也遇到过。
