### ISSUE TITLE
大佬，配置获得失败，有解决办法吗？

### ISSUE THREAD

**Issue by Patrick-Huangweiliang** [gaotianliuyun/gao#146]
1、https://github.com/gaotianliuyun/gao/blob/master/0821.json
2、https://ghproxy.com/https://raw.githubusercontent.com/gaotianliuyun/fongmi/main/json/config.json
大佬，我在影视仓和FM影视输入上面的两个链接，都不能配置成功，像其它的https://gh.t4tv.hz.cz/newtang.bmp接口就可以成功，有什么解决办法吗？
具体提示错误如下：
![image](https://github.com/gaotianliuyun/gao/assets/53536246/55c8cc52-34d5-4065-8099-180276abea91)

**Comment by gaotianliuyun** [comment]
![image](https://github.com/gaotianliuyun/gao/assets/58679624/551736e3-94eb-4225-aaf8-3dc21aee651b)
请使用这样的地址

**Comment by gaotianliuyun** [comment]
第二条地址，是我Fork FongMi的仓库里面的配置，你可以使用原作者的配置地址，或者使用
  https://ghproxy.com/https:/raw.githubusercontent.com/gaotianliuyun/gao/master/0827.json

**Comment by Patrick-Huangweiliang** [comment]
> 配置没有任何问题，使用配置地址时，内地需要添加代理前缀。比如： https://ghproxy.com/https:/raw.githubusercontent.com/gaotianliuyun/gao/master/0821.json 我看了你这个配置地址不是使用的raw地址，而是blob地址。你给我看的第二个地址就是加代理前缀后的地址。

谢谢大佬，问题完美解决
