### ISSUE TITLE
tokengo.txt  的格式来一个 谢谢

### ISSUE THREAD

**Issue by zwm001** [gaotianliuyun/gao#152]
tokengo.txt  的格式来一个 谢谢

**Comment by zwm001** [comment]
找到了   {
"token":"85xxxxxxxxxxxxxxxxxxxxxx",
"open_token":"eyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"thread_limit":32,
"vod_flags":"4k|4kz|auto",
"aliproxy":"http://192.168.101.1:10078",
"proxy":"",
"open_api_url":"https://api.xhofe.top/alist/ali_open/"
}

**Comment by gaotianliuyun** [comment]
现在我PG配置里的ext指向文件换名了，不叫tokengo.txt，而是token.json，不要弄错了，而且你的格式里少了一项夸克的cookie。详细格式我贴在下面。
{
"token":"阿里32位token",
"open_token":"阿里280位token",
"thread_limit":32,
"vod_flags":"4k|4kz|fhd|hd|auto",
"aliproxy":"",
"proxy":"",
"open_api_url":"https://api.xhofe.top/alist/ali_open/",
"quark_cookie":"夸克网盘的cookie"
}
