### ISSUE TITLE
之前的0820是不是没了？

### ISSUE THREAD

**Issue by yankai1009** [gaotianliuyun/gao#154]
RT……

**Comment by gaotianliuyun** [comment]
是的，已经改名0821了，这应该是1月前的事了吧。

**Comment by yankai1009** [comment]
> 是的，已经改名0821了，这应该是1月前的事了吧。

谢谢，请问我用q215613905的版本，使用0825之外的配置，一直提示Too many follow-up requests: 21，这该如何解决。0825也是提示jar加载失败

**Comment by gaotianliuyun** [comment]
我手机里暂时没有纯q版，有皮皮虾的q版，我测试了一下，载入0821，0825，js  几个配置，都没有问题。如果你用fongmi影视正常载入没问题的话，应该不是配置的问题。
我的配置里使用了一些路飞和PG的源，他们的源对tvbox兼容性不是很好。所以我首要推荐fongmi的影视。

**Comment by yankai1009** [comment]
> 我手机里暂时没有纯q版，有皮皮虾的q版，我测试了一下，载入0821，0825，js 几个配置，都没有问题。如果你用fongmi影视正常载入没问题的话，应该不是配置的问题。 我的配置里使用了一些路飞和PG的源，他们的源对tvbox兼容性不是很好。所以我首要推荐fongmi的影视。

额， 我认真看了下，我现在的是0HalfLife0o页面里的q215613905版本，这个应该就是您说的纯q版吧……因为0HalfLife0o页面里面就两种，一个takagen99，一个q215613905。
至于fongmi，我加=进了fongmi_release，但是没发现在哪下载……T-T

**Comment by gaotianliuyun** [comment]
给你一个fongmi影视发布频道https://t.me/tvb_ys

**Comment by yankai1009** [comment]
> 给你一个fongmi影视发布频道https://t.me/tvb_ys
感谢，这个频道我也有看过，但是没看到leanback-java-armeabi_v7a 这类的文件，只有“影视 5.1+电视内测版(py32)20230904”，这个应该可以用在TV上吧？因为昨晚试着安装了影视2.05，然后发现是手机端的……
PS：fongmi_release频道这个是不是只是纯通知的，没有看到发布的消息，倒是您说的tvb_ys里有

**Comment by yankai1009** [comment]
感谢，溜了一圈，确实fongmi_release频道没有发布，您说的这个频道才有（我之前就在这频道逛，但是因为错下成手机版，误以为没有TV版）
