### ISSUE TITLE
播放阿里云盘的资源提示请求超限

### ISSUE THREAD

**Issue by lifenglsf** [gaotianliuyun/gao#169]
已经配置token在tvfan/token.txt中，使用0822的资源，首页配置玩偶或者jojo的资源，搜索田耕纪，出现的资源都是小纸条的，播放的时候提升请求超限。配置的token是新的token，么有使用过呢，是因为分享的资源看的人太多了嘛

**Comment by gaotianliuyun** [comment]
0822搜索没有问题，你看看是不是你将某些原搜索屏蔽了。![Screenshot_20231104_223359.jpg](https://github.com/gaotianliuyun/gao/assets/58679624/ac573cf8-17e3-4cc1-b13b-b8952d8543c9)

![Screenshot_20231104_223615.jpg](https://github.com/gaotianliuyun/gao/assets/58679624/baec23d1-2222-444d-af52-b81bb67ee547)

关于0822的配置，是个极简的配置，本身源就不多。

**Comment by lifenglsf** [comment]
不清楚具体原因是什么，发现有的资源小纸条是可以观看的。电视上用的，也不知道怎么屏蔽
