### ISSUE TITLE
不知道为什么不能回复问题

### ISSUE THREAD

**Issue by klcb2010** [gaotianliuyun/gao#17]
建议取消的是一起看YQK，建议增加小纸条资源，来自fengmi https://ghproxy.com/raw.githubusercontent.com/FongMi/CatVodSpider/main/json/config.json

**Comment by gaotianliuyun** [comment]
我刚刚打开0820.json和0820.txt的一起看推荐的第一个黑豹2，分辨率1920x804，秒播，没有任何问题。你说的小纸条，这两个配置也都有，能正常观看，但是小纸条确实有时不是很稳定，这个需要用到阿里token，现在全网用的都是饭太硬的token，快被褥秃了。
我仓库的jar包和配置都是从网上搬运各个大佬的，也基本保持同步，在0820.json和0820.txt的两个配置里加上质量较好的影视源和直播源。原来我常常暴力缝合一些jar包，现在大佬已经弄得很好了，没必要再折腾了。你上面所说的FongMi的配置我也移植到我的仓库里了，就是0827.json。另外道长的js源、菜尼丝的xBPQ源我仓库里都有，具体请看仓库的README.md，祝你观影愉快。
