### ISSUE TITLE
s什么情况，弹窗提示请下载蜂蜜影视TV，强制关闭

### ISSUE THREAD

**Issue by mlcs-top** [gaotianliuyun/gao#187]
s什么情况，弹窗提示请下载蜂蜜影视TV，强制关闭

**Comment by gaotianliuyun** [comment]
这个情况好像是用了OK大佬的jar，他老人家的包里加了特制代码，只适配蜂蜜影视TV，其中0822.json用的他的主jar，0821.json部分资源外挂了他的jar。

**Comment by mlcs-top** [comment]
嗯，OK明确只支持蜂蜜

**Comment by klcb2010** [comment]
> 这个情况好像是用了OK大佬的jar，他老人家的包里加了特制代码，只适配蜂蜜影视TV，其中0822.json用的他的主jar，0821.json部分资源外挂了他的jar。 当然这只是我的猜测，因为我并没有用影视之外的其他APP。:)

你的猜测是对的  就是这个原因导致闪退

**Comment by klcb2010** [comment]
> 嗯，OK明确只支持蜂蜜

![ok](https://github.com/gaotianliuyun/gao/assets/32628414/73867ae9-fb44-4613-bae5-e33dffedd67c)
你试一下 替换成这个文件 应该没问题了
