### ISSUE TITLE
PG和OK的JAR不能推送视频了     其他几个接口都可以推送

### ISSUE THREAD

**Issue by 3194819809** [gaotianliuyun/gao#192]
如题  例如B站 虎牙这些推送都看不了

**Comment by gaotianliuyun** [comment]
刚刚推送了阿里，pg和ok两个配置都可以正常推送。你说的bili和虎牙，没有连接没有测试。
不过据我所知，bili和虎牙的推送需要有可用的解析。bili我曾经推送过，虎牙我没有推送过。

**Comment by 3194819809** [comment]
麻烦测试下 感谢 https://m.bilibili.com/video/BV1Tp4y1o7Be
