### ISSUE TITLE
0822的土豆网盘等资源，挂了

### ISSUE THREAD

**Issue by klcb2010** [gaotianliuyun/gao#209]
如题 ：，OK自己的链接没问题，怀疑是jar 变了

**Comment by gaotianliuyun** [comment]
刚刚测试了一下，土豆网盘正常的。刚更新的jar，看OK的配置上有所以我也加上了。

**Comment by gaotianliuyun** [comment]
这个是ok大佬的jar，他加上了弹窗，如果介意就用其他的。:^)
