### ISSUE TITLE
大佬请问tvbox的配置怎么用啊

### ISSUE THREAD

**Issue by L585858** [gaotianliuyun/gao#210]

**Comment by gaotianliuyun** [comment]
置顶有教程

**Comment by L585858** [comment]
> 置顶有教程

大佬我没找到啊是哪个啊🥲

**Comment by gaotianliuyun** [comment]
https://github.com/gaotianliuyun/gao/issues/22

**Comment by L585858** [comment]
> https://github.com/gaotianliuyun/gao/issues/22

原来是这个啊，我有看到过，谢谢大佬
