### ISSUE TITLE
虎牙直播

### ISSUE THREAD

**Issue by aoyurs** [gaotianliuyun/gao#27]
首先感谢老哥的维护，然后从自己日常使用的情况中发现了一个小问题，0821中的虎牙直播出不来数据，老哥有空麻烦给看看，感谢！

**Comment by gaotianliuyun** [comment]
刚刚看了，虎牙js确实不能用了。我赶紧看了看猫爪的本地源的和我的js.json，其中的虎牙js同样都不能用了。这样的话原因就是原来的源失效了，不用着急，等大佬修了我会立即更新。
我刚刚又看了0821.json中的网红直播、直播justlive[js]这两个源中都有虎牙直播，你点开筛选，有更多的分类，可以精确选择到你喜欢的类别。同时0821的直播线路有两个虎牙，分别是YanG虎牙和肥羊虎牙。这些暂时可以作替代。
祝观影愉快！

**Comment by gaotianliuyun** [comment]
在我的手机上测试，虎牙直播.js在DMBox、T版TVBox可以正常播放，但是在FongMi版影视上就会出现没有播放数据的情况。我的js.json和猫爪的本地包都是同样的问题。

**Comment by gaotianliuyun** [comment]
卸载重装影视APP可以解决虎牙直播.js不能播放的问题！

**Comment by aoyurs** [comment]
好的，感谢耐心回复，祝生活开心！
