### ISSUE TITLE
大佬，我用的Pluto导入0820提示插件加载失败

### ISSUE THREAD

**Issue by rebron1900** [gaotianliuyun/gao#3]
这些配置需要特殊版本的才能使用吗？

**Comment by gaotianliuyun** [comment]
我的配置里未加入任何pluto配置插件。pluto里的首页插件、alist插件、每日金句插件，需要将代码写入到配置文件里。
但是我的配置即使没有pluto配置插件，也可以在pluto壳上正常使用的。

**Comment by rebron1900** [comment]
我用fastgit的代理线路访问会出现提示插件加载错误的问题，用github原生的raw链接可以正常加载，可能是fastgit的问题

**Comment by gaotianliuyun** [comment]
我没用过fastgit的代理线路，具体情况不了解。
