### ISSUE TITLE
请问老旧设备中兴B860A使用https配置文件地址出现ssl握手失败怎么解决

### ISSUE THREAD

**Issue by thincen** [gaotianliuyun/gao#4]
zxv10 B860a （2016年设备）出现此问题，家里其他设备没有问题

**Comment by rebron1900** [comment]
大佬，jar包下载好后要放在那个目录里呢？

**Comment by gaotianliuyun** [comment]
> zxv10 B860a （2016年设备）出现此问题，家里其他设备没有问题

设备兼容的问题我也没有良策。

**Comment by gaotianliuyun** [comment]
> 大佬，jar包下载好后要放在那个目录里呢？

如果fork到自己仓库的话，不用作任何更改，直接使用配置文件。如果下载本地的话，保证目录结构不变，即可以使用配置文件。配置里全部使用的是相对地址，不受保存位置限制。

**Comment by ttchan414** [comment]
我有同样的问题, 上传到机顶盒使用解决源配置问题。
pull下来的代码在另一个linux设备上, 请问可以在配置中clan://linuxIP/path/gao/xx.json吗？
或者在linux中设置crontab自动更新, 然后curl -X POST 机顶盒IP:9978之类的操作吗
