### ISSUE TITLE
0820解析失效

### ISSUE THREAD

**Issue by jijinli777** [gaotianliuyun/gao#6]
{"name":"野","type":1,"url":"http://newjiexi.gotka.top/keyu3.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},

**Comment by gaotianliuyun** [comment]
刚刚测试了，可以用。

**Comment by jijinli777** [comment]
刚恢复了！

**Comment by jijinli777** [comment]
谢谢！
