### ISSUE TITLE
兄弟，新手，配置文件夹要怎么用？

### ISSUE THREAD

**Issue by mqliutie** [gaotianliuyun/gao#8]
我在某个GitHub搞了一堆json，我以为直接设置json就行，但是客户端提示 media not support我大致说下我的操作

首先当贝市场传上去box安装
然后在电脑版访问host地址，创建文件夹，上传了json
回到电视端选择对应json。提示media。not suoport

**Comment by gaotianliuyun** [comment]
没怎么看懂，看着你操作好复杂！电脑版访问host地址  是什么？

你可以在TVBox、或者影视  设置里填入地址“[https://ghproxy.com/https://raw.githubusercontent.com/gaotianliuyun/gao/master/0820.json](https://ghproxy.com/https:/raw.githubusercontent.com/gaotianliuyun/gao/master/0820.json)”
也就本仓库的配置地址。就可以使用了！

你也可以自己在“https://github.com"建仓库，然后上传json文件，TVBox、或者影视  设置里填入地址即可。记住https://github.com的地址不能直接使用，需要使用”https://ghproxy.com“等类似的代理，使用方法见上。

**Comment by mqliutie** [comment]
我知道你这种操作， 我现在也是这么做的

电脑浏览器访问的host地址是 **我的路由器ip地址加上9978端口号**，就是在设置页不是有一个二维码提示可以手机扫或者电脑登录一个地址么， 我是用电脑登录的那个地址

但是我觉得使用这种远程地址内容都是人家写死的， 我想自定义配置下

我看它支持本地的配置文件， 你看我们现在用的远程连接地址也是个`json`, 我天真的以为把这`json`上传到电视上，选择一下就行了😂

后来有查找了一下， 好像还要有`jar`包， 所以不是很懂， 目前我用的是远程地址配置的

**Comment by gaotianliuyun** [comment]
[配置本地化小程序.zip](https://github.com/gaotianliuyun/gao/files/10370110/default.zip)
我明白了，你是想配置本地化，这是Local大佬的本地化小程序，你试试看，本地化之前先要将json文件中的相对地址改成绝对地址。本地化不光需要json  jar  文件，还需要各种规则下的（比如xbpq  xbiubiu  xyqbiu等）视频源json文件。
这里有个Local大佬的频道”https://t.me/TVBoxLocal/1589“，里面有很多本地包，自己也可以修改上传。
希望能帮助到你！

**Comment by mqliutie** [comment]
OK， 谢大佬
